### ISSUE TITLE
Overhaul

### ISSUE THREAD

**Issue by Appsurdgames** [YoYoGames/GMEXT-WebView#1]
I am currently working on a complete overhaul of the WebView extension. What would be the best approach to contribute to this extension? Just push all of my changes, or do you prefer to talk about it first?

**Comment by stuckie** [comment]
A Pull Request with explanations of the changes will be fine.
Though be aware that if it is a large-scale pull request, it may take a while to go through.

Thanks.

**Comment by YYDan** [comment]
Please always file an issue here and document your intended change _thoroughly_ inside the issue. Await the issue being triaged and set to do, THEN do your pull request from your fork.

Simply adding the pull request is fine for you and the reviewer, but no-one else knows you did it / it wouldn't be in any release notes, etc. It also makes it FAR faster to go through the review process if you have documented what you're changing and why.

Thanks.
